

#url: jdbc:postgresql://localhost:5432/BookRental
#username: postgres
#password: 1234

#    url: jdbc:postgresql://dpg-covnqsa1hbls73du0fj0-a.singapore-postgres.render.com/demobookrentalsabeen
#username: sabeen
#password: GUfjjJo6ssjfXWNNgs6Jkgf0GkuQJQeP

spring:
  datasource:
    # url: jdbc:postgresql://dpg-covnqsa1hbls73du0fj0-a.singapore-postgres.render.com/demobookrentalsabeen
    # username: sabeen
    # password: GUfjjJo6ssjfXWNNgs6Jkgf0GkuQJQeP
    # driver-class-name: org.postgresql.Driver
     url: jdbc:postgresql://ep-shy-snowflake-a1dg4thr.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: qTZRi7X6AkzM
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: bibek.bhattarai831@gmail.com
    password: bppd jkwk krrf lccv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true  #converts underscore of db into camelcase